version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: coaster_app_prod
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    env_file:
      - .env.prod
    environment:
      - APP_ENV=production
      - CI_ENVIRONMENT=production
    depends_on:
      - redis
    networks:
      - coaster_net

  web:
    image: nginx:stable
    container_name: coaster_nginx_prod
    ports:
      - "8090:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - coaster_net

  redis:
    image: redis:alpine
    container_name: coaster_redis_prod
    ports:
      - "6380:6379"
    networks:
      - coaster_net

networks:
  coaster_net:
    driver: bridge
